[package]
name = "better-mic"
version = "0.2.5"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cpal = "0.18"
rtrb = "0.4"
nnnoiseless = "0.5"
libloading = "0.9"
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_Media_KernelStreaming",
    "Win32_Media_Multimedia",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Threading",
] }
tauri-plugin-autostart = "2.7.0"
tauri-plugin-single-instance = "2.5.2"

[profile.release]
strip = true

[profile.dev]
opt-level = 2
